name: doggy-kitty contributor

on:
  schedule:
    - cron: "* * * * *"

  

jobs:
  create_commit:
    runs-on: ubuntu-latest 
    steps:
      - name: Create random file
        run: |
          git init
          git remote add origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
          git config --global user.email "mukul0000kumar@gmail.com"
          git config --global user.name "Clash-ion"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          echo $RANDOM >> random.txt
          var=$(shuf -n 1 names.txt)
          ls -a
          shuf -n 1 names.txt > output
          git add -A
          git commit -m "$var updated your github >.<"
          git push
